workflows:
  react-native-ios:
    name: React Native iOS
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: myapp17247
    environment:
      ios_signing:
        distribution_type: development
        bundle_identifier: com.anonymous.myapp17247
      vars:
        BUNDLE_ID: "com.anonymous.myapp17247" 
        XCODE_WORKSPACE: "myapp17247.xcworkspace" 
        XCODE_SCHEME: "myapp17247" 
    scripts:
      - name: Install npm dependencies
        script: | 
          npm install
      - name: Run Expo Prebuild
        script: | 
          npx expo prebuild
      - name: Install CocoaPods dependencies
        script: | 
          cd ios && pod install
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Build ipa for distribution
        script: | 
          xcode-project build-ipa \
            --workspace "$CM_BUILD_DIR/ios/$XCODE_WORKSPACE" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM